apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jenkins-x/sso-operator:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: install
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/sso-operator:{{.VERSION}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: sso-operator
        chartPath: charts/sso-operator
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/sso-operator"
          image.tag: "{{.TAG}}"
        
