# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 10.15.250.183:5000/jenkins-x/sso-operator
  tag: 0.0.29
  pullPolicy: IfNotPresent
service:
  name: sso-operator
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

dex:
  grpcHostAndPort: dex:5000 
  certs:
    grpc:
      issuer:
        name: dex-dex-grpc-issuer
      client:
        secretName: dex-grpc-client-cert
